### PR TITLE
added spotify dark theme

### PR DESCRIPTION
**Pull request by AOSXAP**

### CODE REVIEW

**Comment by echoriiku** [comment]
A dedicated code block theme would be a great addition. The [Default Dark](https://github.com/streetwriters/notesnook-themes/blob/main/themes/default-dark/v1/code-block.css) code-block CSS theme could serve as a good starting point. Additionally, consider adding a background color to the selected note in the list view. Using the same `#212121` as the main section's backdrop might provide a cohesive look.

**Comment by AOSXAP** [comment]
I am not sure how to generate the code-block CSS from the JSON. In the theme builder the CSS field is empty.

**Comment by revsuine** [comment]
Add a `code-block.css` file with your prismjs theme in the same directory as your `theme.json`

**Comment by echoriiku** [comment]
To create your custom code block theme, you can start by copying the Default Dark code block CSS as a base. Make your desired changes to this CSS, then paste the final code into the code block field provided by the theme builder.
Also regarding the theme name "Spotify", let's wait for feedback from @thecodrr  before proceeding.

**Comment by thecodrr** [comment]
Yeah the name will need to be changed. Spotify is a trademark and it can create issues for us. I suggest something different.

**Comment by AOSXAP** [comment]
Changed Theme name to green glow and also added code-block.css

**Comment by thecodrr** [comment]
@echoriiku can you take a look if all is ok? A little busy right now.

**Comment by echoriiku** [comment]
> Changed Theme name to green glow and also added code-block.css
Looks good @AOSXAP, just change the theme description, still "Spotify" there and we're good to go

**Comment by AOSXAP** [comment]
@echoriiku done, thanks

**Pull request merged**
